#!/bin/bash
# Part of LowSars (pre-azalea) - Lightweight OI Wonderful Scoring And Ranking System
# Usage: ./lowsars-ufmerge CTLS PROBNAMELS NEWFILE OLDFILE ANSFILE (See below)
# credit: chinatslsz@hotmail.com
#
a='"Uniform" format, no i18n:
lsz yh ryh cyh
plus minus multiply divide
lsz plus 1 0.123 10 Accepted.

lsz plus 2 0.456 0 Wrong Answer.
<error message>
lsz plus 3 1.234 0 Time Limit Exceeded.
<killed>
...
lsz plus total 50
lsz minus 1 0.321 10 Accepted.
...
...
lsz divide total 80
lsz total 230
yh plus ...
...
cyh total 210
2007 12 02 19 22'
show_version(){
 echo "LowSars 0.2.0 alpha";
}
ctls="$1"
probnamels="$2"
{
   read 
} 3< "$3" 4< "$4" 5> "$5"