#!/bin/bash
# Translate Cena config file to Lowsars config file
xslfile=/usr/share/lowsars/cena.xsl
[ -f "$1" ]||{
   echo "Please specify the dataconf.xml file as the parameter." >&2
   exit 2
}
cenafile="$1"
cd "`dirname "$cenafile"`"
cenafile="`basename "$cenafile"`"
gunzip -d "$cenafile" 2>/dev/null
lowsarsfile=../dataconf.lsc
xsltproc "$xslfile" "$cenafile" | {
    read x
    cat
}| tr \\ / > $lowsarsfile
