#!/bin/bash
msgprefix="Pascal: "
included=$((${#BASH_SOURCE[@]}>1))
[ "$included" = "1" ]||tell(){
echo "$msgprefix$1"
}
case $1 in
  1)tell "Invalid function number";;
  2)tell "File not found";;
  3)tell "Path not found";;
  4)tell "Too many open files";;
  5)tell "File access denied";;
  6)tell "Invalid file handle";;
  12)tell "Invalid file access code";;
  15)tell "Invalid drive number";;
  16)tell "Cannot remove current directory";;
  17)tell "Cannot rename across drives";;
  100)tell "Disk read error";;
  101)tell "Disk write error";;
  102)tell "File not assigned";;
  103)tell "File not open";;
  104)tell "File not open for input";;
  105)tell "File not open for output";;
  106)tell "Invalid numeric format";;
  150)tell "Disk is write-protected";;
  151)tell "Bad drive request struct length";;
  152)tell "Drive not ready";;
  154)tell "CRC error in data";;
  156)tell "Disk seek error";;
  157)tell "Unknown media type";;
  158)tell "Sector Not Found";;
  159)tell "Printer out of paper";;
  160)tell "Device write fault";;
  161)tell "Device read fault";;
  162)tell "Hardware failure";;
  200)tell "Division by zero";;
  201)tell "Range check error";;
  202)tell "Stack overflow error";;
  203)tell "Heap overflow error";;
  204)tell "Invalid pointer operation";;
  205)tell "Floating point overflow";;
  206)tell "Floating point underflow";;
  207)tell "Invalid floating point operation";;
  210)tell "Object not initialized";;
  211)tell "Call to abstract method";;
  212)tell "Stream registration error";;
  213)tell "Collection index out of range";;
  214)tell "Collection overflow error";;
  215)tell "Arithmetic overflow error";;
  216)tell "General Protection fault";;
  217)tell "Unhandled exception occurred";;
  219)tell "Invalid typecast";;
  227)tell "Assertion failed error";;
  *)if [ "$included" = "1" ]; then return 1; else exit 1; fi;;
esac

if [ "$included" = "1" ]; then return 0; else exit 0; fi

