#!/bin/sh

# List all the languages
LANGS=zh_CN
POFILE=lowsars
# Merge kmess.pot messages for each language
# (same as "cd po; make merge" if you have the Makefiles
#  generated in the same folder Makefile.in lives)
for lang in $LANGS
do
	echo $lang
	msgmerge -U "$lang/$POFILE.po" "$POFILE.pot"
done
