#!/bin/sh

# List all the languages
langs=`cat langs`
f=lowsars
# Merge kmess.pot messages for each language
# (same as "cd po; make merge" if you have the Makefiles
#  generated in the same folder Makefile.in lives)
for lang in $langs
do
	echo $lang
	msgfmt -f $lang/$f.po -o $lang/$f.mo
done
